-- 이거 하기 전에 꼭 c드라이브에 TEAM3DATA 폴더 만들어 놓고 시작

CREATE TABLESPACE TBS_TEAM3
DATAFILE 'C:\TEAM3DATA\TBS_TEAM3.DBF' 
SIZE 4M 
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
--==>> TABLESPACE TBS_TEAM3이(가) 생성되었습니다.



CREATE USER TEAM3 IDENTIFIED BY java006$
DEFAULT TABLESPACE TBS_TEAM3;
--==>> User TEAM3이(가) 생성되었습니다.

GRANT CREATE SESSION TO TEAM3;
--==>> Grant을(를) 성공했습니다.

GRANT CREATE TABLE TO TEAM3;
--==>> Grant을(를) 성공했습니다.

ALTER USER TEAM3
QUOTA UNLIMITED ON TBS_TEAM3;
--==>> User TEAM3이(가) 변경되었습니다.



